services:
  car_rent_postgres:
    container_name: car_rent_postgres
    image: postgres:16
    restart: no
    volumes:
      - ${POSTGRES_VOLUME}
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}